### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pranavbhuv** [QuiverlyRivalry/OneCore#1]
- Make a /hub [DONE]
- Make a /tutorial
- /pvp
- /nightvision

**Comment by jaylac2000** [comment]
suggestion

/pvp  (config: world: world x: x y: y z: z)
/nightvision on/off

**Comment by pranavbhuv** [comment]
I’ll add both of these tomorrow :). If you want to explain more find me here: https://discord.gg/NHr8kx8

**Comment by jaylac2000** [comment]
add tpa system

/fly
