### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by ghost** [QuiverlyRivalry/OneCore#2]
Would you be able to add custom items to it? Like custom potions, custom tnt. And maybe a function in a config where we can set custom items to do certain things, so I’ll give you cam example.

Custom Items:
  MonthlyCrate:
    commands:
      - givemoney {player} 1000
      - givekit {player} Tank

etc and to use these items you just need to right click

**Comment by QuiverlyRivalry** [comment]
I’ll be adding kits tomorrow.

**Comment by QuiverlyRivalry** [comment]
As well as custom potions

**Comment by pranavbhuv** [comment]
Sure. Please explain more in depth, contact me here: https://discord.gg/NHr8kx8.
